vars:
  - params.yaml

stages:
  split:
    cmd: python scripts/preprocess.py --stage split
    deps:
      - ../../data/${experiment.dataset}/
    outs:
      - data/${experiment.name}/raw/train/
      - data/${experiment.name}/raw/test/
    params:
      - params.yaml:
          - experiment
          - preprocessing.train_ratio

  preprocess:
    cmd: python scripts/preprocess.py --stage preprocess
    deps:
      - ../../shared/src/fall_sensing/core/sanitization.py
      - data/${experiment.name}/raw/
    outs:
      - data/${experiment.name}/preprocessed/
    params:
      - params.yaml:
          - preprocessing.hampel_window
          - preprocessing.n_sigma

  extract_features:
    cmd: python scripts/feature_extraction.py
    deps:
      - ../../shared/src/fall_sensing/core/feature.py
      - data/${experiment.name}/preprocessed/
    outs:
      - data/${experiment.name}/features/
    params:
      - params.yaml:
          - feature

  train:
    cmd: python scripts/train.py
    deps:
      - data/${experiment.name}/features/
    outs:
      - data/${experiment.name}/models/best_model.pt
    metrics:
      - data/${experiment.name}/result/metrics.json:
          cache: false
    params:
      - params.yaml:
          - train

  visualize:
    cmd: python scripts/visualize.py
    deps:
      - data/${experiment.name}/models/best_model.pt
      - data/${experiment.name}/features/
    outs:
      - data/${experiment.name}/result/plots/
    params:
      - params.yaml:
          - experiment
